# Generated by Django 5.2.7 on 2025-12-16 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('mustaqil', 'Mustaqil ish'), ('kurs', 'Kurs ishi'), ('diplom', 'Diplom ishi'), ('software', 'Dasturiy vosita')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('topic', models.TextField()),
                ('price', models.IntegerField()),
                ('payment_file', models.FileField(blank=True, null=True, upload_to='payments/')),
                ('status', models.CharField(choices=[('created', 'Yaratildi'), ('payment_wait', 'To‘lov kutilmoqda'), ('payment_sent', 'Chek yuborildi'), ('payment_approved', 'To‘lov tasdiqlandi'), ('taken', 'Ijrochiga berildi'), ('done', 'Yakunlandi')], max_length=30)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('taken_by', models.CharField(blank=True, max_length=255, null=True)),
                ('completed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.user')),
            ],
        ),
    ]
