# Generated by Django 5.2.7 on 2025-12-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='approved_by',
            new_name='result_file_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_file',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='taken_by',
        ),
        migrations.AddField(
            model_name='order',
            name='fullname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to='order_files/'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_telegram_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('IN_PROGRESS', 'Jarayonda'), ('DONE', 'Tayyor')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='topic',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
