# Generated by Django 5.2.7 on 2025-12-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_remove_order_user_remove_order_completed_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='service_type',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='taken_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_telegram_id',
        ),
        migrations.AddField(
            model_name='order',
            name='accepted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
